version: 2

jobs:
     build:
          docker:
               steps:
                    - run: npm run start

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build